# .github/workflows/backend.yml

name: Backend CI/CD (FastAPI)

on:
  push:
    branches:
      - main
      - develop # CI on develop
      - 'feature/**' # CI on feature branches
    paths:
      - 'backend/**'
  pull_request: # CI on pull requests
    branches:
      - main
      - develop
    paths:
      - 'backend/**'

jobs:
  build-and-test: # This is your CI job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      - name: Run backend tests
        run: |
          echo "Backend tests would run here."
      - name: Build Docker image for Backend
        run: |
          docker build -t olabophoto-backend:latest ./backend
          echo "Docker image built successfully for backend."

  deploy: # This is your CD job
    runs-on: ubuntu-latest
    environment: production # Link to your GitHub Environment
    needs: build-and-test # This job now depends on 'build-and-test' within the same file
    if: github.ref == 'refs/heads/main' && success() # Only deploy to production if main branch and previous job succeeded

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Debian Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.DEPLOY_PATH }}
            echo "Pulling latest code..."
            git pull origin main
            echo "Rebuilding and restarting Docker services..."
            docker compose -f docker-compose.yml up -d --build --force-recreate backend db
            echo "Backend deployment complete!"